Repository hassio-addons/addon-tailscale, pull requests merged in 2021-11, with the labels that each got.

#47 Switch to centralized GitHub Action Workflows
  .github/labels.yml
  .github/release-drafter.yml
  .github/workflows/ci.yaml
  .github/workflows/deploy.yaml
  .github/workflows/labels.yaml
  .github/workflows/lock.yaml
  .github/workflows/pr-labels.yaml
  .github/workflows/release-drafter.yaml
  .github/workflows/stale.yaml
Labels: ci

#48 Migrate JSON config to YAML
  tailscale/build.json
  tailscale/build.yaml
  tailscale/config.json
  tailscale/config.yaml
Labels: refactor

#49 ⬆️ Upgrades add-on base image to 10.2.2
  tailscale/Dockerfile
  tailscale/build.yaml
Labels: dependencies

#50 ⬆️ Upgrades Tailscale to 1.16.2
  tailscale/Dockerfile
Labels: dependencies

#41 Add Userspace networking mode flag
  tailscale/rootfs/etc/services.d/tailscaled/run
Labels: bugfix

#54 ⬆️ Upgrades nginx to 1.20.2-r0
  tailscale/Dockerfile
Labels: dependencies

#55 ⬆️ Upgrades add-on base image to 10.2.3
  tailscale/Dockerfile
  tailscale/build.yaml
Labels: dependencies

#56 ⬆️ Upgrades Tailscale to 1.18.0
  tailscale/Dockerfile
Labels: dependencies

#57 Add support for setting ACL tags
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/services.d/tailscaled/post
Labels: new-feature

#58 ⬆️ Upgrades Tailscale to 1.18.1
  tailscale/Dockerfile
Labels: dependencies
