Repository hassio-addons/addon-tailscale, pull requests merged in 2023-03, with the labels that each got.

#145 Add Renovate for dependency management
  .github/dependabot.yaml
  .github/renovate.json
  tailscale/Dockerfile
Labels: maintenance

#155 :fireworks: Updates maintenance/license year to 2023
  LICENSE.md
  README.md
  tailscale/.README.j2
  tailscale/DOCS.md
Labels: maintenance

#156 :hammer: Migrate old-style S6 scripts to s6-rc.d
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/dependencies.d/base
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-nginx/up
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/init-nginx
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/dependencies.d/web
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/dependencies.d/tailscaled
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/up
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/dependencies.d/base
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/init-nginx
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/nginx
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/post-tailscaled
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/tailscaled
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/web
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/dependencies.d/base
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/type
  tailscale/rootfs/etc/services.d/nginx/finish
  tailscale/rootfs/etc/services.d/tailscaled/finish
  tailscale/rootfs/etc/services.d/web/finish
Labels: refactor

#131 Minor bugfixes
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
Labels: bugfix

#158 Bugfix in migrated S6 scripts
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/nginx/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Labels: bugfix

#159 Fix broken URL
  tailscale/DOCS.md
Labels: documentation

#162 🗑️ Move away from Codenotary
  tailscale/build.yaml
  tailscale/config.yaml
Labels: maintenance

#164 Revert "🗑️ Move away from Codenotary (#162)"
  tailscale/build.yaml
  tailscale/config.yaml
Labels: maintenance

#138 Suppress tailscaled logs after 200 lines
  tailscale/DOCS.md
  tailscale/Dockerfile
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Labels: enhancement
