Repository hassio-addons/addon-tailscale, pull requests merged in 2023-10, with the labels that each got.

#198 Create fallback page for iOS browsers failing to open Tailscale login page
  tailscale/rootfs/etc/nginx/templates/ingress.gtpl
Labels: enhancement

#196 Remove duplicate status checks from dependent S6 services
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/taildrop/run
Labels: bugfix

#212 Do not opt out of client log upload in debug log level
  tailscale/DOCS.md
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Labels: enhancement

#240 Rearrange proxy documentation into alphabetical order
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/translations/en.yaml
Labels: documentation

#197 Enable Tailscale's Funnel feature
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/dependencies.d/proxy
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/up
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/funnel
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/translations/en.yaml
Labels: new-feature

#255 Warn about key expiration
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: enhancement

#242 Update Installation section in documentation
  tailscale/DOCS.md
Labels: documentation

#260 Use new .Self.CapMap in status JSON for HTTPS support check
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
Labels: enhancement

#252 make accepting subnet routes optional
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#199 Make userspace networking configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#201 Protect local subnets from being routed toward Tailscale subnets if they collide
  tailscale/DOCS.md
  tailscale/Dockerfile
  tailscale/config.yaml
  tailscale/rootfs/etc/NetworkManager/dispatcher.d/connectivity-change
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/dependencies.d/protect-subnets
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/dependencies.d/base
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/protect-subnets/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/protect-subnets
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/rootfs/usr/bin/protect-subnet-routes
  tailscale/rootfs/usr/bin/subnet-routes
  tailscale/rootfs/usr/bin/unprotect-subnet-routes
Labels: enhancement

#253 Make advertise routes configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/usr/bin/subnet-routes
  tailscale/translations/en.yaml
Labels: new-feature

#222 Clamp the MSS to the MTU for all advertised subnet's interface
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/dependencies.d/post-tailscaled
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/down
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/up
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/mss-clamping
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
Labels: new-feature

#223 Make subnet source NAT configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#275 Fix local subnet protection
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/usr/bin/protect-subnet-routes
  tailscale/rootfs/usr/bin/subnet-routes
Labels: bugfix

#273 Proxy and Funnel are disabled by default
  tailscale/DOCS.md
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/funnel/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/translations/en.yaml
Labels: breaking-change

#274 Documentation improvements
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/translations/en.yaml
Labels: documentation
