Repository hassio-addons/addon-tailscale, pull requests merged in 2023-04, with the labels that each got.

#172 Extend documentation with disabling key expiry
  tailscale/DOCS.md
Labels: documentation

#171 Remove unneeded add-on privileges
  tailscale/config.yaml
Labels: maintenance

#178 Tiny code styling changes
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/web/run
Labels: refactor

#179 Add translations
  tailscale/translations/en.yaml
Labels: enhancement

#180 Add custom control server support
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#182 Fix typo "login_server: unbound variable"
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix

#183 Make exit node advertisement configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#185 Make Taildrop configurable
  tailscale/DOCS.md
  tailscale/Dockerfile
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/translations/en.yaml
Labels: new-feature

#184 Fix login-server option
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix

#188 Add taildrop to example configuration
  tailscale/DOCS.md
Labels: documentation

#192 Device limit update in DOCS.md
  tailscale/DOCS.md
Labels: documentation

#181 Drop userspace networking
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
Labels: new-feature

#194 Make accepting magicDNS optional
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#195 Add docs for accept_dns
  tailscale/DOCS.md
Labels: documentation

#137 Enable Tailscale's builtin inbound HTTPS proxy
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/dependencies.d/post-tailscaled
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/type
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/up
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/user/contents.d/proxy
  tailscale/rootfs/etc/s6-overlay/scripts/stage2_hook.sh
  tailscale/translations/en.yaml
Labels: new-feature
