Repository hassio-addons/addon-tailscale, pull requests merged in 2024-05, with the labels that each got.

#351 Linux optimizations for subnet routers and exit nodes
  tailscale/Dockerfile
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: enhancement

#356 Fix indentation
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: refactor

#348 Add app connector option
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#358 Reword app connector option's translation
  tailscale/translations/en.yaml
Labels: enhancement

#357 Make stateful filtering configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: new-feature

#360 Fix Linux optimizations
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix

#361 Allow Linux optimizations (UDP GRO for forwarding) on multiple default interfaces and IPv6
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix

#366 Skip default networks without a gateway to enable UDP GRO for forwarding
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix

#368 Stateful filtering is now off by default
  tailscale/DOCS.md
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/translations/en.yaml
Labels: enhancement

#370 Failsafe enabling of UDP GRO for forwarding
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
Labels: bugfix
