Repository hassio-addons/addon-tailscale, pull requests merged in 2024-01, with the labels that each got.

#312 :fireworks: Updates maintenance/license year to 2024
  LICENSE.md
  README.md
  tailscale/.README.j2
  tailscale/DOCS.md
Labels: maintenance

#309 Increase wait time for Supervisor
  tailscale/rootfs/usr/bin/protect-subnet-routes
Labels: enhancement

#307 Cleanup ip6tables
  tailscale/Dockerfile
Labels: maintenance

#308 Clamp the MSS for IPv6 also
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run
Labels: bugfix

#277 Make Proxy and Funnel port configurable
  tailscale/DOCS.md
  tailscale/config.yaml
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/serve/run
  tailscale/translations/en.yaml
Labels: new-feature

#313 Use regex for Proxy and Funnel port configuration validation
  tailscale/config.yaml
Labels: enhancement
