Repository hassio-addons/addon-tailscale, pull requests merged in 2025-02, with the labels that each got.

#464 Reformat docs about read-only Web-UI
  tailscale/DOCS.md
Labels: documentation

#452 Don't break sentences into multiple log messages
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
  tailscale/rootfs/usr/bin/protect-subnet-routes
Labels: enhancement

#473 :fireworks: Updates maintenance/license year to 2025
  LICENSE.md
  README.md
  tailscale/.README.j2
  tailscale/DOCS.md
Labels: maintenance

#453 Fix MSS clamping for site-to-site networking
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/finish
  tailscale/rootfs/etc/s6-overlay/s6-rc.d/mss-clamping/run
Labels: bugfix

#457 Update site-to-site networking related documentation
  tailscale/DOCS.md
Labels: documentation
